import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } });
await page.goto('http://localhost:5173/login', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(800);
await page.getByText('Tenant Admin', { exact: false }).first().click();
await page.waitForTimeout(2000);
await page.goto('http://localhost:5173/workspace/settings?s=integrations', { waitUntil: 'networkidle', timeout: 20000 });
await page.waitForTimeout(1200);
await page.screenshot({ path: 'scratch/integrations_page.png', fullPage: true });
console.log('URL:', page.url());
const text = await page.locator('body').innerText();
console.log(text.slice(0, 3000));
await browser.close();
