import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } });
await page.goto('http://localhost:5173/login', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(800);
await page.getByText('Tenant Admin', { exact: false }).first().click();
await page.waitForTimeout(2000);
await page.goto('http://localhost:5173/workspace/settings?s=integrations', { waitUntil: 'networkidle', timeout: 20000 });
await page.waitForTimeout(1000);
await page.getByText('Integrations', { exact: true }).click();
await page.waitForTimeout(600);
await page.screenshot({ path: 'scratch/integrations_expanded.png', fullPage: true });
const text = await page.locator('nav, [class*="sidebar"]').first().innerText().catch(() => page.locator('body').innerText());
console.log(text);
await browser.close();
