#!/usr/bin/env bash
# Regenerates lib/core/dev_host.dart so the app can reach the local dev
# ondi-api backend (:7020) from wherever it's running. Mirrors
# apps/mobile/ondi/scripts/dev_host.sh — see that file for the full
# rationale (adb reverse for device/emulator, LAN IP fallback otherwise).
#
# Run this once per device/session before `flutter run`:
#   ./scripts/dev_host.sh
set -euo pipefail

ONDI_PORT=7020
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEV_HOST_FILE="$SCRIPT_DIR/../lib/core/dev_host.dart"

write_dev_host() {
  cat > "$DEV_HOST_FILE" <<EOF2
// Auto-generated by scripts/dev_host.sh. Do not commit.
const String devHostIp = '$1';
EOF2
  echo "Wrote devHostIp = '$1' to lib/core/dev_host.dart"
}

if command -v adb >/dev/null 2>&1; then
  DEVICES=$(adb devices | awk 'NR>1 && $2=="device" {print $1}')
else
  DEVICES=""
fi

if [ -n "$DEVICES" ]; then
  echo "Android device(s) found via adb — setting up reverse tunnels:"
  while IFS= read -r serial; do
    [ -z "$serial" ] && continue
    adb -s "$serial" reverse "tcp:$ONDI_PORT" "tcp:$ONDI_PORT"
    echo "  $serial: tcp:$ONDI_PORT -> localhost"
  done <<< "$DEVICES"
  write_dev_host "localhost"
  echo "Note: re-run this script whenever the app is reinstalled or adb reconnects."
else
  LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || true)"
  if [ -z "$LAN_IP" ]; then
    LAN_IP="$(ipconfig getifaddr en1 2>/dev/null || true)"
  fi
  if [ -z "$LAN_IP" ]; then
    echo "No adb device found and couldn't detect a LAN IP (en0/en1)." >&2
    echo "Set one manually, e.g.: echo \"const String devHostIp = '192.168.x.x';\" > lib/core/dev_host.dart" >&2
    exit 1
  fi
  echo "No adb device found — falling back to LAN IP (requires same Wi-Fi + firewall access to node)."
  write_dev_host "$LAN_IP"
fi
