// ─── hugeicons-map.ts — IconName → real Hugeicons free-tier artwork ───
// Every entry below was checked against the actual installed
// @hugeicons/core-free-icons package (node_modules — 6,031 real exports),
// not guessed from a name. That package ships far more icons than this
// platform has names for, so this file intentionally does NOT cover every
// IconName — only the ones with an unambiguous, verified real match. Any
// name missing here falls back to the stroke set (Icon.tsx handles that),
// the same way the hand-authored `twotone` library already does for its
// smaller 25-name set. Only imported by IconAlt.tsx, which is loaded on
// demand (not from the app's main bundle) — see Icon.tsx's comment on why.
import type { IconSvgElement } from '@hugeicons/react';
import type { IconName } from './Icon.js';
import {
  Activity01Icon, AlertCircleIcon, Alert02Icon, AnchorIcon, Archive01Icon,
  ArrowDown01Icon, ArrowLeft01Icon, ArrowRight01Icon, ArrowUp01Icon, ArrowUpDownIcon, ArrowUpRight01Icon,
  AtSignIcon, Award01Icon, BanknoteIcon, BellIcon, BoltIcon, BookOpen01Icon, Bookmark01Icon,
  Briefcase01Icon, Building01Icon, CalculatorIcon, Calendar03Icon, Camera01Icon,
  Tick01Icon, CheckmarkCircle02Icon, ChevronDownIcon, ChevronLeftIcon, ChevronRightIcon, ChevronUpIcon,
  CircleIcon, ClipboardIcon, Clock01Icon, Cancel01Icon, ClosedCaptionIcon, CloudRainIcon, Coins01Icon,
  Compass01Icon, Contact01Icon, ContainerIcon, Copy01Icon, CreditCardIcon, CrownIcon,
  DollarSignIcon, DotIcon, Download04Icon, PencilEdit01Icon, ExternalLinkIcon, EyeIcon, EyeOffIcon,
  File01Icon, FilterIcon, Folder01Icon, GlobeIcon, GridIcon, HashtagIcon, HeadphonesIcon, HelpCircleIcon,
  Home01Icon, Image01Icon, InboxIcon, InformationCircleIcon, Key01Icon, Layers01Icon, Leaf01Icon,
  Link01Icon, LockIcon, LogInIcon, LogOutIcon, Mail01Icon, MapIcon, MapPinIcon, Maximize01Icon,
  Menu01Icon, Message01Icon, Mic01Icon, Minimize01Icon, MinusSignIcon, MinusSignCircleIcon, Moon01Icon,
  MoreHorizontalIcon, MoreVerticalIcon, Package01Icon, PauseIcon, PercentCircleIcon, PhoneIcon,
  PieChart01Icon, PinIcon, Airplane01Icon, PlayIcon, PlusSignIcon, AddCircleIcon, PrinterIcon, PuzzleIcon,
  ReceiptIcon, SaveIcon, ScaleIcon, ScanIcon, Search01Icon, SendIcon, Setting07Icon, Share01Icon,
  Shield01Icon, ShipIcon, ShoppingCart01Icon, SidebarLeftIcon, SirenIcon, SlidersHorizontalIcon,
  SmartPhone01Icon, SmileIcon, SparkleIcon, StarIcon, Sun01Icon, Tag01Icon, Target01Icon, Task01Icon,
  Timer01Icon, Train01Icon, TrashIcon, TrendingDownIcon, TrendingUpIcon, DeliveryTruck01Icon,
  Upload04Icon, UserIcon, UserCheck01Icon, UserMinus01Icon, UserPlusIcon, UserGroupIcon,
  Wallet01Icon, MagicWand01Icon, WarehouseIcon, MultiplicationSignIcon, CancelCircleIcon, ZapIcon,
} from '@hugeicons/core-free-icons';

export const HUGEICONS_MAP: Partial<Record<IconName, IconSvgElement>> = {
  activity: Activity01Icon,
  alertCircle: AlertCircleIcon,
  alertTriangle: Alert02Icon,
  anchor: AnchorIcon,
  archive: Archive01Icon,
  arrowDown: ArrowDown01Icon,
  arrowLeft: ArrowLeft01Icon,
  arrowRight: ArrowRight01Icon,
  arrowUp: ArrowUp01Icon,
  arrowUpDown: ArrowUpDownIcon,
  arrowUpRight: ArrowUpRight01Icon,
  atSign: AtSignIcon,
  award: Award01Icon,
  bankNote: BanknoteIcon,
  bell: BellIcon,
  bolt: BoltIcon,
  bookOpen: BookOpen01Icon,
  bookmark: Bookmark01Icon,
  briefcase: Briefcase01Icon,
  building: Building01Icon,
  calculator: CalculatorIcon,
  calendar: Calendar03Icon,
  camera: Camera01Icon,
  check: Tick01Icon,
  checkCircle: CheckmarkCircle02Icon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  circle: CircleIcon,
  clipboard: ClipboardIcon,
  clock: Clock01Icon,
  close: Cancel01Icon,
  closedCaptions: ClosedCaptionIcon,
  cloudRain: CloudRainIcon,
  coins: Coins01Icon,
  compass: Compass01Icon,
  contact: Contact01Icon,
  container: ContainerIcon,
  copy: Copy01Icon,
  creditCard: CreditCardIcon,
  crown: CrownIcon,
  dollarSign: DollarSignIcon,
  dot: DotIcon,
  download: Download04Icon,
  edit: PencilEdit01Icon,
  externalLink: ExternalLinkIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  file: File01Icon,
  filter: FilterIcon,
  folder: Folder01Icon,
  globe: GlobeIcon,
  grid: GridIcon,
  hash: HashtagIcon,
  headphones: HeadphonesIcon,
  helpCircle: HelpCircleIcon,
  home: Home01Icon,
  image: Image01Icon,
  inbox: InboxIcon,
  info: InformationCircleIcon,
  key: Key01Icon,
  layers: Layers01Icon,
  leaf: Leaf01Icon,
  link: Link01Icon,
  lock: LockIcon,
  logIn: LogInIcon,
  logOut: LogOutIcon,
  mail: Mail01Icon,
  map: MapIcon,
  mapPin: MapPinIcon,
  maximize: Maximize01Icon,
  menu: Menu01Icon,
  message: Message01Icon,
  mic: Mic01Icon,
  minimize: Minimize01Icon,
  minus: MinusSignIcon,
  minusCircle: MinusSignCircleIcon,
  moon: Moon01Icon,
  moreHorizontal: MoreHorizontalIcon,
  moreVertical: MoreVerticalIcon,
  package: Package01Icon,
  pause: PauseIcon,
  percent: PercentCircleIcon,
  phone: PhoneIcon,
  pieChart: PieChart01Icon,
  pin: PinIcon,
  plane: Airplane01Icon,
  play: PlayIcon,
  plus: PlusSignIcon,
  plusCircle: AddCircleIcon,
  printer: PrinterIcon,
  puzzle: PuzzleIcon,
  receipt: ReceiptIcon,
  save: SaveIcon,
  scale: ScaleIcon,
  scan: ScanIcon,
  search: Search01Icon,
  send: SendIcon,
  settings: Setting07Icon,
  share: Share01Icon,
  shield: Shield01Icon,
  ship: ShipIcon,
  shoppingCart: ShoppingCart01Icon,
  sidebar: SidebarLeftIcon,
  siren: SirenIcon,
  sliders: SlidersHorizontalIcon,
  smartphone: SmartPhone01Icon,
  smile: SmileIcon,
  sparkle: SparkleIcon,
  star: StarIcon,
  sun: Sun01Icon,
  tag: Tag01Icon,
  target: Target01Icon,
  tasks: Task01Icon,
  timer: Timer01Icon,
  train: Train01Icon,
  trash: TrashIcon,
  trendingDown: TrendingDownIcon,
  trendingUp: TrendingUpIcon,
  truck: DeliveryTruck01Icon,
  upload: Upload04Icon,
  user: UserIcon,
  userCheck: UserCheck01Icon,
  userMinus: UserMinus01Icon,
  userPlus: UserPlusIcon,
  users: UserGroupIcon,
  wallet: Wallet01Icon,
  wand: MagicWand01Icon,
  warehouse: WarehouseIcon,
  x: MultiplicationSignIcon,
  xCircle: CancelCircleIcon,
  zap: ZapIcon,
};
