import { withTenant } from '../db/client.js';
import { getNextDocNumber } from '../lib/doc-numbering.js';
import { GLService } from './gl.service.js';
import { AccountingIntegrationService } from './accounting-integration.service.js';

/** Same four frequencies Bills.tsx's own advanceDate() has always supported —
 *  kept identical so a template behaves the same whether it's generated by
 *  a human clicking "Generate now" or by the daily job. */
function advanceDate(dateStr: string, frequency: string): string {
  const d = new Date(dateStr);
  if (frequency === 'WEEKLY') d.setDate(d.getDate() + 7);
  else if (frequency === 'QUARTERLY') d.setMonth(d.getMonth() + 3);
  else if (frequency === 'ANNUAL') d.setFullYear(d.getFullYear() + 1);
  else d.setMonth(d.getMonth() + 1); // MONTHLY, and the fallback for anything unrecognised
  return d.toISOString().slice(0, 10);
}

export interface GenerationResult {
  generated: { templateId: string; documentId: string; documentNumber: string; amount: number }[];
  skipped: { templateId: string; reason: string }[];
}

/**
 * Generates a real bill from every due, active recurring_bills template for
 * a tenant — the same logic Bills.tsx's own handleGenerate() button has
 * always run client-side (build a payload, POST /v1/bills, then PATCH the
 * template's counters), lifted server-side so a daily job can call it too.
 */
export async function generateDueBills(tenantId: string, today = new Date().toISOString().slice(0, 10), templateId?: string): Promise<GenerationResult> {
  return withTenant(tenantId, async (trx) => {
    let q = trx.selectFrom('recurring_bills').selectAll()
      .where('tenant_id', '=', tenantId).where('state', '=', 'ACTIVE');
    // A manual "Generate now" targets one template regardless of its due
    // date (matching the button's pre-existing behavior); the daily job
    // omits templateId and only picks up what's actually due.
    q = templateId ? q.where('id', '=', templateId) : q.where('next_due', '<=', today);
    const due = await q.execute();

    const result: GenerationResult = { generated: [], skipped: [] };
    for (const r of due) {
      if (r.end_date && r.end_date < today) {
        result.skipped.push({ templateId: r.id, reason: 'past end date' });
        continue;
      }
      const amount = Number(r.amount) || 0;
      if (amount <= 0) {
        result.skipped.push({ templateId: r.id, reason: 'template has no amount' });
        continue;
      }

      const billNumber = `BILL-${Date.now()}-${r.id.slice(0, 4)}`;
      const taxAmount = amount * (Number(r.tax_rate) || 0) / 100;
      const total = amount + taxAmount;

      const bill = await trx.insertInto('supplier_bills').values({
        tenant_id: tenantId,
        bill_number: billNumber,
        supplier_id: r.supplier_id,
        supplier_name: r.supplier_name,
        bill_date: r.next_due,
        due_date: r.next_due,
        status: 'POSTED',
        currency: r.currency,
        subtotal: amount,
        tax_amount: taxAmount,
        total,
        paid_amount: 0,
        recurring_id: r.id,
        notes: `Generated from recurring template "${r.name || r.supplier_name}".`,
      }).returningAll().executeTakeFirstOrThrow();

      await trx.insertInto('supplier_bill_lines').values({
        bill_id: bill.id,
        description: r.description || r.name || 'Recurring charge',
        category: r.category,
        qty: 1,
        unit_price: amount,
        tax_rate: Number(r.tax_rate) || 0,
        tax_code_id: r.tax_code_id,
      } as any).execute();

      if (total > 0) {
        await GLService.post(tenantId, {
          entryDate: r.next_due ?? today,
          description: `Supplier bill: ${bill.bill_number}`,
          reference: bill.bill_number,
          sourceModule: 'AP',
          sourceId: bill.id,
          lines: [
            { accountCode: accountForBillCategory(r.category), debit: amount + taxAmount, credit: 0, description: 'Recurring charge' },
            { accountCode: '2000', debit: 0, credit: total, description: 'Accounts payable' },
          ],
        });
      }

      await trx.insertInto('bill_activity_log').values({
        tenant_id: tenantId, bill_id: bill.id, actor_id: null, actor_name: 'Recurring billing',
        action: 'created', detail: `Bill ${bill.bill_number} generated from recurring template "${r.name || r.supplier_name}"`,
      }).execute();

      AccountingIntegrationService.syncBill(tenantId, bill.id).catch(() => {});

      await trx.updateTable('recurring_bills').set({
        next_due: advanceDate(r.next_due ?? today, r.frequency),
        bills_generated: (r.bills_generated ?? 0) + 1,
        total_spend: Number(r.total_spend ?? 0) + total,
        updated_at: new Date(),
      }).where('id', '=', r.id).execute();

      result.generated.push({ templateId: r.id, documentId: bill.id, documentNumber: bill.bill_number, amount: total });
    }
    return result;
  });
}

/** The AR counterpart — generates a real invoice from every due, active
 *  recurring_invoices template. */
export async function generateDueInvoices(tenantId: string, today = new Date().toISOString().slice(0, 10), templateId?: string): Promise<GenerationResult> {
  return withTenant(tenantId, async (trx) => {
    let q = trx.selectFrom('recurring_invoices').selectAll()
      .where('tenant_id', '=', tenantId).where('state', '=', 'ACTIVE');
    q = templateId ? q.where('id', '=', templateId) : q.where('next_due', '<=', today);
    const due = await q.execute();

    const result: GenerationResult = { generated: [], skipped: [] };
    for (const r of due) {
      if (r.end_date && r.end_date < today) {
        result.skipped.push({ templateId: r.id, reason: 'past end date' });
        continue;
      }
      const amount = Number(r.amount) || 0;
      if (amount <= 0) {
        result.skipped.push({ templateId: r.id, reason: 'template has no amount' });
        continue;
      }

      const invoiceNumber = await getNextDocNumber(trx, tenantId, 'invoice');
      const taxAmount = amount * (Number(r.tax_rate) || 0) / 100;
      const total = amount + taxAmount;

      const inv = await trx.insertInto('sales_invoices').values({
        tenant_id: tenantId,
        invoice_number: invoiceNumber,
        customer_id: r.customer_id,
        client_name: r.client_name,
        client_address: '[]',
        bill_date: r.next_due,
        due_date: r.next_due,
        payment_terms: r.payment_terms,
        status: 'Unpaid',
        currency: r.currency,
        notes: `Generated from recurring template "${r.name || r.client_name}".`,
      } as any).returningAll().executeTakeFirstOrThrow();

      await trx.insertInto('sales_invoice_lines').values({
        invoice_id: inv.id,
        name: r.description || r.name || 'Recurring charge',
        unit: 'PER BIL',
        rate: amount,
        qty: 1,
        tax_pct: Number(r.tax_rate) || 0,
        tax_code_id: r.tax_code_id,
        line_group: 'other',
        currency: r.currency,
        sort_order: 0,
      } as any).execute();

      await GLService.post(tenantId, {
        entryDate: r.next_due ?? today,
        description: `Invoice: ${inv.invoice_number}`,
        reference: inv.invoice_number,
        sourceModule: 'AR',
        sourceId: inv.id,
        lines: [
          { accountCode: '1100', debit: total, credit: 0, description: 'Accounts receivable' },
          { accountCode: '4500', debit: 0, credit: amount, description: 'Recurring revenue' },
          ...(taxAmount > 0 ? [{ accountCode: '2200', debit: 0, credit: taxAmount, description: 'VAT output' }] : []),
        ],
      });

      await trx.insertInto('invoice_activity_log').values({
        tenant_id: tenantId, invoice_id: inv.id, actor_id: null, actor_name: 'Recurring billing',
        action: 'created', detail: `Invoice ${inv.invoice_number} generated from recurring template "${r.name || r.client_name}"`,
      }).execute();

      AccountingIntegrationService.syncInvoice(tenantId, inv.id).catch(() => {});

      await trx.updateTable('recurring_invoices').set({
        next_due: advanceDate(r.next_due ?? today, r.frequency),
        invoices_generated: (r.invoices_generated ?? 0) + 1,
        total_billed: Number(r.total_billed ?? 0) + total,
        updated_at: new Date(),
      }).where('id', '=', r.id).execute();

      result.generated.push({ templateId: r.id, documentId: inv.id, documentNumber: inv.invoice_number, amount: total });
    }
    return result;
  });
}

/** Identical to bills.routes.ts's own (unexported) CATEGORY_ACCOUNT map —
 *  duplicated rather than imported since that file's map is a private
 *  const, and the two lists needing to agree is the only real coupling. */
const CATEGORY_ACCOUNT: Record<string, string> = {
  FREIGHT: '5001', CUSTOMS: '5000', PORT: '5000', TRANSPORT: '5002',
  WAREHOUSE: '5003', UTILITIES: '5102', PROFESSIONAL: '5100', INSURANCE: '5000', OTHER: '5000',
};
function accountForBillCategory(category: string | null | undefined): string {
  return CATEGORY_ACCOUNT[String(category ?? '').toUpperCase()] ?? '5000';
}
