// ─── Digital Execution Seal, Phase 6 — formal forensic report ─────────────────
// A single, self-contained PDF an investigator can hand to someone who
// never opens this platform: the verdict, every piece of evidence and its
// hash, the full analysis history (Phase 6's own versioning — see
// sign-forensic-case.service.ts's recordAnalysisRun), and the complete
// chain of custody, in one document. Built with pdf-lib, matching the
// visual language sign-pdf.service.ts already established for every other
// document this platform produces (teal accent bar, HUDUMIKA wordmark) —
// a new, unrelated look for this one PDF would read as a different
// product.
//
// Deliberately plain, honest language throughout (the same posture as
// every other finding surface in this feature): a page number, a
// disclaimer that this is a technical comparison and not a legal
// conclusion, and nothing dressed up to look more authoritative than the
// underlying checks actually are.
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 50;
const TOP_START = PAGE_H - 150;
const BOTTOM = 60;

const INK = rgb(0.06, 0.09, 0.16);
const INK2 = rgb(0.3, 0.32, 0.38);
const INK3 = rgb(0.5, 0.52, 0.58);
const TEAL = rgb(0.02, 0.45, 0.42);
const GREEN = rgb(0.05, 0.5, 0.35);
const GOLD = rgb(0.55, 0.35, 0.05);
const RED = rgb(0.75, 0.15, 0.15);
const BORDER = rgb(0.85, 0.85, 0.85);

const VERDICT_COLOR: Record<string, ReturnType<typeof rgb>> = {
  EXACT_MATCH: GREEN, SEAL_VERIFIED_SCAN_VARIATION_ONLY: GREEN, SEAL_VERIFIED_CONTENT_MATCH: GREEN,
  SEAL_VERIFIED_CONTENT_DIFFERENCE: GOLD, INCONCLUSIVE: INK3,
  SEAL_INVALID: RED, DOCUMENT_MISMATCH: RED,
};

export interface ForensicReportInput {
  kase: {
    id: string; envelope_title: string; verification_code: string; content_verdict: string | null;
    status: string; opened_by_name: string | null; opened_at: Date;
    resolved_at: Date | null; resolution_note: string | null;
    canonical_hash: string | null; manifest_hash: string | null;
  };
  evidence: Array<{ filename: string; source: string; size_bytes: number; sha256: string }>;
  audit: Array<{ action: string; actor_name: string | null; ip_address: string | null; created_at: Date }>; // any order; report re-sorts oldest-first
  analysisRuns: Array<{ run_number: number; content_verdict: string | null; created_at: Date; triggered_by_name: string | null }>;
}

const ACTION_LABEL: Record<string, string> = {
  opened: 'Case opened', uploaded: 'Evidence uploaded', analysis_initiated: 'Analysis started',
  viewed: 'Viewed', exported: 'Evidence exported', status_changed: 'Status changed',
  re_analyzed: 'Re-analyzed', report_generated: 'Report generated',
};

function fmt(d: Date): string {
  return new Date(d).toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
}
function fmtBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}

interface Cursor { doc: PDFDocument; page: PDFPage; y: number; pageNum: number; regular: PDFFont; bold: PDFFont; mono: PDFFont; caseId: string; }

function drawFooter(page: PDFPage, regular: PDFFont, pageNum: number) {
  page.drawLine({ start: { x: MARGIN, y: 42 }, end: { x: PAGE_W - MARGIN, y: 42 }, thickness: 0.5, color: BORDER });
  page.drawText('Automated technical comparison only — not a legal conclusion. Generated by the Hudumika platform.', { x: MARGIN, y: 30, size: 7.5, font: regular, color: INK3 });
  page.drawText(`Page ${pageNum}`, { x: PAGE_W - MARGIN - 40, y: 30, size: 7.5, font: regular, color: INK3 });
}

async function addPage(c: Cursor): Promise<void> {
  c.page = c.doc.addPage([PAGE_W, PAGE_H]);
  c.pageNum += 1;
  c.y = PAGE_H - 60;
  drawFooter(c.page, c.regular, c.pageNum);
}

async function ensureSpace(c: Cursor, needed: number): Promise<void> {
  if (c.y - needed < BOTTOM) await addPage(c);
}

function sectionHeader(c: Cursor, label: string): void {
  c.page.drawText(label.toUpperCase(), { x: MARGIN, y: c.y, size: 10, font: c.bold, color: TEAL });
  c.y -= 6;
  c.page.drawLine({ start: { x: MARGIN, y: c.y }, end: { x: PAGE_W - MARGIN, y: c.y }, thickness: 0.75, color: BORDER });
  c.y -= 16;
}

export async function generateForensicReportPdf(input: ForensicReportInput): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const mono = await doc.embedFont(StandardFonts.Courier);

  const page = doc.addPage([PAGE_W, PAGE_H]);
  const c: Cursor = { doc, page, y: TOP_START, pageNum: 1, regular, bold, mono, caseId: input.kase.id };
  drawFooter(page, regular, 1);

  // ── Header panel ──────────────────────────────────────────────────────
  page.drawRectangle({ x: 0, y: PAGE_H - 90, width: PAGE_W, height: 90, color: rgb(0.98, 0.98, 0.99) });
  page.drawRectangle({ x: 0, y: PAGE_H - 6, width: PAGE_W, height: 6, color: TEAL });
  page.drawText('HUDUMIKA', { x: MARGIN, y: PAGE_H - 40, size: 16, font: bold, color: INK });
  page.drawText('Digital Forensic Report', { x: MARGIN, y: PAGE_H - 60, size: 12, font: regular, color: INK2 });
  const genLine = `Generated ${fmt(new Date())}  ·  Case ${input.kase.id.slice(0, 8)}`;
  page.drawText(genLine, { x: PAGE_W - MARGIN - bold.widthOfTextAtSize(genLine, 8), y: PAGE_H - 40, size: 8, font: mono, color: INK3 });

  // ── Case summary ─────────────────────────────────────────────────────
  sectionHeader(c, 'Case summary');
  const verdictColor = VERDICT_COLOR[input.kase.content_verdict ?? ''] ?? INK3;
  const rows: Array<[string, string, ReturnType<typeof rgb>?]> = [
    ['Envelope', input.kase.envelope_title],
    ['Verification code', input.kase.verification_code],
    ['Opening verdict', (input.kase.content_verdict ?? 'Unknown').replace(/_/g, ' '), verdictColor],
    ['Status', input.kase.status.toUpperCase()],
    ['Opened by', `${input.kase.opened_by_name ?? 'System'} · ${fmt(input.kase.opened_at)}`],
  ];
  if (input.kase.resolved_at) rows.push(['Resolved', fmt(input.kase.resolved_at)]);
  if (input.kase.resolution_note) rows.push(['Resolution note', input.kase.resolution_note]);
  for (const [label, value, color] of rows) {
    await ensureSpace(c, 16);
    page.drawText(label, { x: MARGIN, y: c.y, size: 9, font: regular, color: INK3 });
    c.page.drawText(value, { x: MARGIN + 140, y: c.y, size: 9.5, font: bold, color: color ?? INK, maxWidth: PAGE_W - MARGIN * 2 - 140 });
    c.y -= 16;
  }
  c.y -= 8;

  // ── Hashes ────────────────────────────────────────────────────────────
  await ensureSpace(c, 60);
  sectionHeader(c, 'Cryptographic hashes');
  for (const [label, value] of [['Canonical (SHA-256)', input.kase.canonical_hash], ['Evidence manifest (SHA-256)', input.kase.manifest_hash]] as const) {
    await ensureSpace(c, 16);
    c.page.drawText(label, { x: MARGIN, y: c.y, size: 9, font: regular, color: INK3 });
    c.page.drawText(value ?? '—', { x: MARGIN + 160, y: c.y, size: 8, font: mono, color: INK, maxWidth: PAGE_W - MARGIN * 2 - 160 });
    c.y -= 16;
  }
  c.y -= 8;

  // ── Analysis history (Phase 6 versioning) ───────────────────────────
  await ensureSpace(c, 40);
  sectionHeader(c, `Analysis history (${input.analysisRuns.length} run${input.analysisRuns.length === 1 ? '' : 's'})`);
  for (const run of input.analysisRuns) {
    await ensureSpace(c, 15);
    const col = VERDICT_COLOR[run.content_verdict ?? ''] ?? INK3;
    c.page.drawText(`Run #${run.run_number}`, { x: MARGIN, y: c.y, size: 8.5, font: bold, color: INK });
    c.page.drawText((run.content_verdict ?? 'Unknown').replace(/_/g, ' '), { x: MARGIN + 55, y: c.y, size: 8.5, font: bold, color: col });
    c.page.drawText(`${fmt(run.created_at)} · ${run.triggered_by_name ?? 'System'}`, { x: MARGIN + 220, y: c.y, size: 8, font: regular, color: INK3 });
    c.y -= 15;
  }
  c.y -= 8;

  // ── Evidence ─────────────────────────────────────────────────────────
  await ensureSpace(c, 40);
  sectionHeader(c, `Evidence (${input.evidence.length} file${input.evidence.length === 1 ? '' : 's'})`);
  for (const e of input.evidence) {
    await ensureSpace(c, 26);
    c.page.drawText(e.filename, { x: MARGIN, y: c.y, size: 8.5, font: bold, color: INK, maxWidth: PAGE_W - MARGIN * 2 });
    c.y -= 12;
    c.page.drawText(`${e.source} · ${fmtBytes(e.size_bytes)} · ${e.sha256}`, { x: MARGIN, y: c.y, size: 7, font: mono, color: INK3, maxWidth: PAGE_W - MARGIN * 2 });
    c.y -= 14;
  }
  c.y -= 4;

  // ── Chain of custody (oldest first, for a readable narrative) ──────
  await ensureSpace(c, 40);
  sectionHeader(c, `Chain of custody (${input.audit.length} event${input.audit.length === 1 ? '' : 's'})`);
  const chronological = [...input.audit].sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime());
  for (const ev of chronological) {
    await ensureSpace(c, 14);
    const label = ACTION_LABEL[ev.action] ?? ev.action;
    const line = `${fmt(ev.created_at)}  —  ${label}${ev.actor_name ? ` (${ev.actor_name})` : ''}${ev.ip_address ? `  ·  ${ev.ip_address}` : ''}`;
    c.page.drawText(line, { x: MARGIN, y: c.y, size: 8, font: regular, color: INK2, maxWidth: PAGE_W - MARGIN * 2 });
    c.y -= 14;
  }

  return Buffer.from(await doc.save());
}
