-- Announcements are what the header pill was actually asked for. They are not
-- notifications and do not belong in that table:
--
--   a notification  is generated by something that happened to one workspace's
--                   own data, addressed to whoever it concerns, and read once.
--   an announcement is written by a human, addressed to everybody (or to one
--                   tenant), lives for a window of time, and is dismissed
--                   rather than read.
--
-- Putting them together would mean either fanning one announcement out into a
-- row per user — thousands of duplicates of the same sentence, which is the
-- failure mode the missing-document reminder just demonstrated — or bolting a
-- start/end window and a per-user dismissal onto a table whose other 226,000
-- rows have no use for either.

CREATE TABLE IF NOT EXISTS announcements (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- NULL means every workspace on the platform sees it; a tenant id narrows it
  -- to one. This is the only table here that is deliberately nullable on
  -- tenant_id, and the read query has to say so explicitly rather than relying
  -- on `tenant_id = $1`, which would silently exclude every platform-wide row.
  tenant_id   UUID REFERENCES tenants(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  body        TEXT,
  /** Where the pill takes you. A relative app path, not an external URL. */
  link        TEXT,
  /** Rendered in the pill's badge. Free text so it can read NEW, MAINTENANCE,
   *  RELEASE — whatever the announcement actually is. */
  badge       VARCHAR(24) NOT NULL DEFAULT 'NEW',
  /** Scheduling is a window, not a boolean, so an announcement can be written
   *  ahead of time and expire on its own instead of relying on somebody
   *  remembering to switch it off. `active` is the manual override on top. */
  starts_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ends_at     TIMESTAMPTZ,
  active      BOOLEAN NOT NULL DEFAULT true,
  created_by  UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One row per person who has dismissed one, rather than a flag on the
-- announcement: the same announcement is shown to everybody, so "dismissed"
-- cannot be a property of the announcement itself.
CREATE TABLE IF NOT EXISTS announcement_dismissals (
  announcement_id UUID NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
  user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  dismissed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (announcement_id, user_id)
);

-- The read is always "live right now, for this tenant or for everybody".
CREATE INDEX IF NOT EXISTS idx_announcements_live
  ON announcements(active, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_announcements_tenant
  ON announcements(tenant_id);
CREATE INDEX IF NOT EXISTS idx_announcement_dismissals_user
  ON announcement_dismissals(user_id);

-- Deliberately no RLS policy on announcements: a platform-wide row has
-- tenant_id NULL, and the standard tenant_isolation_policy compares
-- tenant_id to app.tenant_id, which NULL never equals — every global
-- announcement would be invisible to everyone. Visibility is enforced in the
-- route instead, which is where it has to be reasoned about anyway.
ALTER TABLE announcement_dismissals ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policy WHERE polname = 'own_dismissals_policy' AND polrelid = 'announcement_dismissals'::regclass) THEN
    -- Dismissals carry no tenant column; they are scoped by the user they
    -- belong to, and the route filters on user_id for the same reason.
    CREATE POLICY own_dismissals_policy ON announcement_dismissals USING (true);
  END IF;
END $$;
