import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import type { FinanceExpenseReport } from '@hudumika/types';
import { apiFetch } from '../lib/api.js';
import { useAuth } from '../hooks/useAuth.js';
import { PageHeader } from '../components/PageHeader.js';
import { PersonAvatar } from '../components/PersonAvatar.js';
import { Button } from '../components/ui/button.js';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card.js';
import { Input } from '../components/ui/input.js';
import { Label } from '../components/ui/label.js';
import { EntityPicker, type PickerItem } from '../components/EntityPicker.js';
import { Badge } from '../components/ui/badge.js';
import { DatePicker, parseDateOnly, toDateOnlyString } from '../components/ui/date-picker.js';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '../components/ui/select.js';
import './FinanceIndustries.css';

const base = '/v1/finance/expense-reports';
const states = ['all', 'draft', 'submitted', 'approved', 'rejected', 'reimbursed'];
const money = (value: number) => new Intl.NumberFormat('en-TZ', { style: 'currency', currency: 'TZS' }).format(value);
export function FinanceExpenseReports() {
  const [rows, setRows] = useState<FinanceExpenseReport[]>([]); const [page, setPage] = useState(1); const [status, setStatus] = useState('all'); const [more, setMore] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { let live = true; setLoading(true); apiFetch<{ data: FinanceExpenseReport[]; has_more: boolean }>(`${base}?page=${page}&status=${status}`).then(result => { if (live) { setRows(result.data); setMore(result.has_more); setError(''); } }).catch(err => { if (live) setError(err.message); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [page, status]);
  return <div className="industry-page"><PageHeader crumbs={['Finance', 'Expenses']} titlePlain="Expense" titleEm="reports" subtitle="Submit receipts, review claims and record employee reimbursements." actions={<Button asChild><Link to="/finance/expense-reports/new">New report</Link></Button>} />
    <div className="industry-field"><Label>Status</Label><Select value={status} onValueChange={value => { setStatus(value); setPage(1); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{states.map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div>
    {error && <p role="alert">{error}</p>}{loading ? <p role="status">Loading reports…</p> : <div className="industry-hub-grid">{rows.map(row => <Card key={row.id}><CardHeader><CardTitle>{row.name}</CardTitle></CardHeader><CardContent><Badge>{row.status}</Badge><p>{new Date(row.created_at).toLocaleDateString()}</p><Button asChild variant="outline"><Link to={`/finance/expense-reports/${row.id}`}>View report</Link></Button></CardContent></Card>)}{!rows.length && <p>No reports in this view.</p>}</div>}
    <div className="industry-actions"><Button variant="outline" disabled={page === 1 || loading} onClick={() => setPage(value => value - 1)}>Previous</Button><span>Page {page}</span><Button variant="outline" disabled={!more || loading} onClick={() => setPage(value => value + 1)}>Next</Button></div>
  </div>;
}
export function FinanceExpenseReportNew() {
  const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const navigate = useNavigate();
  return <div className="industry-page"><PageHeader crumbs={[{ label: 'Finance', to: '/finance' }, { label: 'Expense reports', to: '/finance/expense-reports' }, 'New']} titlePlain="New expense" titleEm="report" subtitle="Start a TZS report, then add receipt-backed claims." />{error && <p role="alert">{error}</p>}<Card><CardContent className="pt-6"><form className="industry-page" onSubmit={async event => { event.preventDefault(); setBusy(true); try { const report = await apiFetch<FinanceExpenseReport>(base, { method: 'POST', body: JSON.stringify({ name }) }); navigate(`/finance/expense-reports/${report.id}`); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create report.'); } finally { setBusy(false); } }}><div><Label htmlFor="report-name">Report name</Label><Input id="report-name" value={name} required maxLength={160} onChange={event => setName(event.target.value)} /></div><div className="industry-form-actions"><Button disabled={busy || !name.trim()}>Create report</Button></div></form></CardContent></Card></div>;
}
export function FinanceExpenseReportDetail() {
  const { id } = useParams(); const { user } = useAuth(); const [report, setReport] = useState<FinanceExpenseReport>(); const [revision, setRevision] = useState(0); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [name, setName] = useState(''); const [amount, setAmount] = useState(''); const [category, setCategory] = useState('MISCELLANEOUS'); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [receipt, setReceipt] = useState(''); const [preview, setPreview] = useState(''); const [note, setNote] = useState(''); const [reference, setReference] = useState('');
  const [customer, setCustomer] = useState<PickerItem | null>(null); const [supplier, setSupplier] = useState<PickerItem | null>(null);
  const findCustomers = useCallback(async (search: string) => {
    const result = await apiFetch<{ data: { id: string; name: string; active: boolean }[] }>(`/v1/customers?limit=20&search=${encodeURIComponent(search)}`);
    return result.data.filter(item => item.active).map(item => ({ id: item.id, label: item.name }));
  }, []);
  const findSuppliers = useCallback(async (search: string) => {
    const result = await apiFetch<{ id: string; name: string }[]>(`/v1/suppliers?limit=20&status=active&search=${encodeURIComponent(search)}`);
    return result.map(item => ({ id: item.id, label: item.name }));
  }, []);
  useEffect(() => { let live = true; apiFetch<FinanceExpenseReport>(`${base}/${id}`).then(result => { if (live) setReport(result); }).catch(err => { if (live) setError(err.message); }); return () => { live = false; }; }, [id, revision]);
  async function action(suffix: string, body?: object) {
    setBusy(true); setError(''); try { await apiFetch(`${base}/${id}/${suffix}`, { method: 'POST', body: body ? JSON.stringify(body) : undefined }); setRevision(value => value + 1); setPreview(''); return true; } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save report.'); return false; } finally { setBusy(false); }
  }
  const owned = report?.owner_id === user?.id; const editable = owned && ['draft', 'rejected'].includes(report?.status || '');
  const canReview = ['SUPER_ADMIN', 'ADMIN', 'TENANT_ADMIN', 'FINANCE'].includes(user?.role || '') && !owned;
  const canPay = ['SUPER_ADMIN', 'ADMIN', 'TENANT_ADMIN', 'FINANCE'].includes(user?.role || '');
  return <div className="industry-page"><PageHeader crumbs={[{ label: 'Finance', to: '/finance' }, { label: 'Expense reports', to: '/finance/expense-reports' }, report?.name || 'Report']} titlePlain="Expense" titleEm="report" subtitle={report ? `${report.name} · ${report.status}` : 'Loading report…'} actions={editable && <Button disabled={busy || !report?.items?.length} onClick={() => action('submit')}>Submit report</Button>} />
    {error && <p role="alert">{error}</p>}{report && <><Card><CardHeader><CardTitle>{money(report.items?.reduce((sum, item) => sum + Number(item.amount), 0) || 0)}</CardTitle></CardHeader><CardContent><p>{report.review_note}</p><p>{report.payment_reference && `Reimbursement reference: ${report.payment_reference}`}</p><div className="industry-hub-grid">{report.items?.map(item => <Card key={item.id}><CardContent className="pt-6"><strong>{item.name}</strong>{item.customer_id && <p><Link className="industry-check" to={`/crm/customers/${item.customer_id}`}><PersonAvatar userId={item.customer_id} kind="customers" name={item.customer_name || "Customer"} size={28} />{item.customer_name || "Customer"}</Link></p>}{item.supplier_id && <p><Link className="industry-check" to={`/crm/vendors/${item.supplier_id}`}><PersonAvatar userId={item.supplier_id} kind="suppliers" name={item.supplier_name || "Vendor"} size={28} />{item.supplier_name || "Vendor"}</Link></p>}<p>{item.expense_date} · {item.category} · {money(Number(item.amount))}</p><Button variant="outline" onClick={async () => { try { const data = await apiFetch<{ receipt_data: string }>(`${base}/${id}/items/${item.id}/receipt`); setPreview(data.receipt_data); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load receipt.'); } }}>View receipt</Button></CardContent></Card>)}</div>{preview && <img src={preview} alt="Claim receipt" style={{ maxWidth: '100%', maxHeight: 600, objectFit: 'contain' }} />}</CardContent></Card>
      {editable && <Card><CardHeader><CardTitle>Add receipt</CardTitle></CardHeader><CardContent><form className="industry-page" onSubmit={async event => { event.preventDefault(); if (await action('items', { name, amount: Number(amount), category, expense_date: date, receipt_data: receipt, customer_id: customer?.id ?? null, supplier_id: supplier?.id ?? null })) { setName(''); setAmount(''); setReceipt(''); } }}><div className="industry-form-grid"><div><Label htmlFor="claim-name">Expense</Label><Input id="claim-name" required value={name} onChange={event => setName(event.target.value)} maxLength={255} /></div><div><Label htmlFor="claim-amount">Amount (TZS)</Label><Input id="claim-amount" type="number" required min="0.01" max="10000000000" step="0.01" value={amount} onChange={event => setAmount(event.target.value)} /></div><div><Label htmlFor="claim-category">Category</Label><Input id="claim-category" required maxLength={50} value={category} onChange={event => setCategory(event.target.value)} /></div><div><Label>Expense date</Label><DatePicker date={parseDateOnly(date)} onChange={value => setDate(value ? toDateOnlyString(value) : '')} /></div></div><div className="industry-form-grid"><EntityPicker label="CRM customer (optional)" value={customer} onChange={setCustomer} search={findCustomers} placeholder="Search CRM customers" disabled={busy} /><EntityPicker label="CRM vendor (optional)" value={supplier} onChange={setSupplier} search={findSuppliers} placeholder="Search shared vendors" disabled={busy} /></div><div><Label htmlFor="claim-receipt">Receipt (PNG or JPEG, up to 700 KB)</Label><Input id="claim-receipt" type="file" accept="image/png,image/jpeg" onChange={event => { const file = event.target.files?.[0]; setReceipt(''); if (!file) return; if (file.size > 700000 || !['image/png', 'image/jpeg'].includes(file.type)) { setError('Choose a PNG or JPEG up to 700 KB.'); return; } const reader = new FileReader(); reader.onload = () => setReceipt(String(reader.result)); reader.readAsDataURL(file); }} /></div><p>Receipts are required. Exact duplicate receipt files are blocked across the workspace.</p><div className="industry-form-actions"><Button disabled={busy || !receipt || !date}>Add claim</Button></div></form></CardContent></Card>}
      {canReview && report.status === 'submitted' && <Card><CardHeader><CardTitle>Finance review</CardTitle></CardHeader><CardContent className="industry-page"><Label htmlFor="claim-review">Review note</Label><Input id="claim-review" maxLength={2000} value={note} onChange={event => setNote(event.target.value)} /><div className="industry-actions"><Button disabled={busy || !note.trim()} onClick={() => action('review', { approve: true, note })}>Approve report</Button><Button variant="outline" disabled={busy || !note.trim()} onClick={() => action('review', { approve: false, note })}>Reject report</Button></div><p>Approval records expense and employee payable together. It does not transfer money.</p></CardContent></Card>}
      {canPay && report.status === 'approved' && <Card><CardHeader><CardTitle>Record reimbursement</CardTitle></CardHeader><CardContent className="industry-page"><p>Record an already completed TZS bank payment. This posts to bank account 1010 and clears employee payable 2100.</p><Label htmlFor="claim-reference">Bank payment reference</Label><Input id="claim-reference" value={reference} maxLength={160} onChange={event => setReference(event.target.value)} /><Label>Payment date</Label><DatePicker date={parseDateOnly(date)} onChange={value => setDate(value ? toDateOnlyString(value) : '')} /><div className="industry-form-actions"><Button disabled={busy || !reference.trim() || !date} onClick={() => action('reimburse', { reference, date })}>Record reimbursement</Button></div></CardContent></Card>}
    </>}
  </div>;
}
